repositories:
- name: istio
  url: https://istio-release.storage.googleapis.com/charts
helmfiles:
  - path: helmfiles/istio-base/helmfile.yaml
  - path: helmfiles/istiod/helmfile.yaml
  - path: helmfiles/istio-ingress/helmfile.yaml
