appName: belajar-istio

domain: istio.local

services:
  - name: auth
    isPublic: true
    withAuth: false
    path: /auth
    container:
      image: rizalord/istio-auth-service:latest
      port: 
        service: 
          - 3000
        container: 
          http: 3000
      env:
        - name: USER_SERVICE_HOST
          value: user-service
        - name: USER_SERVICE_PORT
          value: 3001
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  - name: user
    isPublic: false
    path: null
    withAuth: false
    container:
      image: rizalord/istio-user-service:latest
      port: 
        service: 
          - 3003
          - 3001
        container: 
          http: 3003
          tcp: 3001
      env: 
        - name: NODE_ENV
          value: production
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  - name: analytic
    isPublic: true
    path: /analytic
    withAuth: true
    container:
      image: rizalord/istio-analytic-service:latest
      port: 
        service: 
          - 3002
        container: 
          http: 3002
      env:
        - name: USER_SERVICE_HOST
          value: user-service
        - name: USER_SERVICE_PORT
          value: 3001
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

istio:
  auth:
    jwtRules:
    - issuer: "testing@istio.local"
      jwksUri: "http://auth-service.default.svc.cluster.local:3000/.well-known/jwks.json"
  
  mtls: 
    mode: STRICT

  gateway:
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
          - "istio.local"

  virtual:
    host: "istio.local"
    http:
      - uri: /auth
        destination: auth-service
      - uri: /analytic
        destination: analytic-service