stages:
  - build

variables:
  USER_IMAGE_NAME: $REGISTRY_USERNAME/istio-user-service
  USER_IMAGE_TAG: latest

build-image-user-service:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DEPOT_TOKEN: $DEPOT_TOKEN
  before_script:
    - apk add --no-cache curl
    - curl https://depot.dev/install-cli.sh | DEPOT_INSTALL_DIR=/usr/local/bin sh
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd user-service
    - docker build -t $USER_IMAGE_NAME:$USER_IMAGE_TAG .
    - docker push $USER_IMAGE_NAME:$USER_IMAGE_TAG
    # - depot build --project td1mkrfjz6 -t $USER_IMAGE_NAME:$USER_IMAGE_TAG . --push