stages:
  - build

variables:
  USER_IMAGE_NAME: $REGISTRY_USERNAME/istio-user-service
  USER_IMAGE_TAG: latest
  AUTH_IMAGE_NAME: $REGISTRY_USERNAME/istio-auth-service
  AUTH_IMAGE_TAG: latest
  ANALYTICS_IMAGE_NAME: $REGISTRY_USERNAME/istio-analytic-service
  ANALYTICS_IMAGE_TAG: latest

build-image-user-service:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DEPOT_TOKEN: $DEPOT_TOKEN
  before_script:
    - apk add --no-cache curl
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - cd services/user-service
    - docker build -t $USER_IMAGE_NAME:$USER_IMAGE_TAG .
    - docker push $USER_IMAGE_NAME:$USER_IMAGE_TAG

build-image-auth-service:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DEPOT_TOKEN: $DEPOT_TOKEN
  before_script:
    - apk add --no-cache curl
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - cd services/auth-service
    - docker build -t $AUTH_IMAGE_NAME:$AUTH_IMAGE_TAG .

build-image-analytic-service:
  stage: build
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DEPOT_TOKEN: $DEPOT_TOKEN
  before_script:
    - apk add --no-cache curl
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - cd services/analytic-service
    - docker build -t $ANALYTICS_IMAGE_NAME:$ANALYTICS_IMAGE_TAG .
    - docker push $ANALYTICS_IMAGE_NAME:$ANALYTICS_IMAGE_TAG