apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: analytic-request-authentication
  namespace: default
spec:
  selector:
    matchLabels:
      app: analytic-pod
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://gist.githubusercontent.com/lordofthejars/7dad589384612d7a6e18398ac0f10065/raw/ea0f8e7b729fb1df25d4dc60bf17dee409aad204/jwks.json"

---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: analytic-authorization-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: analytic-pod
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
