{{ range .Values.services }}
{{ if .withAuth }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .name }}-authorization-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .name }}-pod
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]

{{ end }}
{{ end }}