# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: jwt-auth-policy
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: analytic-deployment
#   rules:
#   - from:
#     - source:
#         requestPrincipals: ["*"]