{{ range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .name }}-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .name }}-pod
        version: v1
    spec:
      containers:
      - name: {{ .name }}-container
        image: {{ .container.image }}
        imagePullPolicy: IfNotPresent
        ports:
        {{ range .container.port.service }}
        - containerPort: {{ .port | int }}
        {{ end }}
        envFrom:
          - secretRef:
              name: {{ .name }}-secret
        livenessProbe:
          {{ if .container.port.container.http }}
          httpGet:
            path: /health
            port: {{ .container.port.container.http | int }}
          {{ else if .container.port.container.tcp }}
          tcpSocket:
            port: {{ .container.port.container.tcp | int }}
          {{ end }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          {{ if .container.port.container.http }}
          httpGet:
            path: /health
            port: {{ .container.port.container.http | int }}
          {{ else if .container.port.container.tcp }}
          tcpSocket:
            port: {{ .container.port.container.tcp | int }}
          {{ end }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        resources: {{ .resources | toYaml | nindent 10 }}
{{- end }}