{{ range .Values.services }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .name }}-destination-rule
spec:
  host: {{ .name }}-service
  subsets:
  - name: v1
    labels:
      version: v1

{{ end }}