apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.appName }}-gw
  labels:
    app: {{ .Values.appName }}-gw
spec:
  selector:
    istio: ingressgateway
  servers: {{ .Values.istio.gateway.servers | toYaml | nindent 4 }}