apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  deployment:
    view_only_mode: false
  server:
    web_root: "/kiali"
  external_services:
    prometheus:
      url: http://prometheus-server.metrics.svc.cluster.local
    grafana:
      in_cluster_url: http://grafana.metrics.svc.cluster.local