apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-mtls
  namespace: default
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}

---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: auth-mtls
  namespace: default
spec:
  selector:
    matchLabels:
      app: auth-pod
  mtls:
    mode: PERMISSIVE