{{ range .Values.services }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
type: Opaque
data:
  {{ range .container.env }}
  {{ .name }}: {{ .value | toString | b64enc }}
  {{ end }}

{{ end }}