{{ range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  labels:
    app: {{ .name }}-service
spec:
  type: NodePort
  ports:
  {{ range .container.port.service }}
  - port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
    name: "{{ .protocol}}-{{ .port }}"
  {{ end }}
  selector:
    app: {{ .name }}-pod

{{ end }}