apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
spec:
  hosts:
  - {{ .Values.istio.virtual.host }}
  gateways:
  - {{ .Values.appName }}-gw
  http:
  {{ range .Values.istio.virtual.http }}
  - match:
    - uri:
        prefix: {{ .uri }}/
    - uri:
        exact: {{ .uri }}
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ .destination }}
        subset: v1
  {{ end }}